conditionalPanel(
  condition = "output.condition_distribution == true",

fluidRow(column(9, 
                tabsetPanel(type = "tabs",
                            id = "plotpanel",
                            tabPanel("Make a Forecast", plotlyOutput("p_distr", height = "800px")),
                            tabPanel("For Reference: Daily Cases",
                                     plotlyOutput("plot_cases", height = "800px")))),
         column(3, 
                offset = 0,
                style = 'padding: 20px; background-color: aliceblue',
                
                fluidRow(column(8, htmlOutput("name_field")), 
                         column(4, HTML('To request a change of your user information, please write us an <a href= "mailto:nikos.bosse@lshtm.ac.uk">email</a>'))),
                
                br(),
                fluidRow(column(12, h3("Forecasts"))),
                
                
                fluidRow(column(12, selectInput(inputId = "distribution", 
                                                label = "Select distribution", 
                                                choices = c("log-normal", 
                                                            "normal", 
                                                            "cubic-normal", 
                                                            "fifth-power-normal", 
                                                            "seventh-power-normal"), 
                                                selected = "log-normal"))),
                fluidRow(column(4, 
                                numericInput(inputId = "median_forecast_1", 
                                             value = 0,
                                             label = "Median 1", 
                                             step = 10)),
                         column(4, 
                                numericInput(inputId = "width_1", 
                                             value = 0,
                                             label = "Width 1", 
                                             step = 0.01)), 
                         column(4, 
                                actionButton(inputId = "propagate_1", "Propagate", 
                                             style = 'margin-top: 25px'))
                ), 
                fluidRow(column(4, 
                                numericInput(inputId = "median_forecast_2", 
                                             value = 0,
                                             label = "Median 2", 
                                             step = 10)),
                         column(4, 
                                numericInput(inputId = "width_2", 
                                             value = 0,
                                             label = "Width 2", 
                                             step = 0.01)), 
                         column(4, 
                                actionButton(inputId = "propagate_2", "Propagate", 
                                             style = 'margin-top: 25px'))
                ), 
                fluidRow(column(4, 
                                numericInput(inputId = "median_forecast_3", 
                                             value = 0,
                                             label = "Median 3", 
                                             step = 10)),
                         column(4, 
                                numericInput(inputId = "width_3", 
                                             value = 0,
                                             label = "Width 3", 
                                             step = 0.01)), 
                         column(4, 
                                actionButton(inputId = "propagate_3", "Propagate", 
                                             style = 'margin-top: 25px'))
                ), 
                fluidRow(column(4, 
                                numericInput(inputId = "median_forecast_4", 
                                             value = 0,
                                             label = "Median 4", 
                                             step = 10)),
                         column(4, 
                                numericInput(inputId = "width_4", 
                                             value = 0,
                                             label = "Width 4", 
                                             step = 0.01)), 
                         column(4, 
                                actionButton(inputId = "update_1", HTML('<b>Update</b>'), 
                                             style = 'margin-top: 25px')))
                
                
                ,
                br(),
                fluidRow(column(3, actionButton("submit", label = HTML('<b>Submit</b>'))), 
                         column(12, "(Please click 'update' before submitting)")), 
                br(), 
                br(), 
                br(), 
                fluidRow(column(12, textInput(inputId = "comments", 
                                              label = "Do you have any additional comments, suggestions, feedback?"))), 
                fluidRow(column(12, HTML('Preferably, you can submit an issue on <a href="https://github.com/epiforecasts/covid-german-forecasts">github</a>')))
         )
)

)