# UI for quantile condition
conditionalPanel(
  condition = "output.condition_quantile",
  
  fluidRow(column(8, 
                  tabsetPanel(type = "tabs",
                              id = "plotpanel",
                              tabPanel("Make a Forecast", plotlyOutput("p_quant", height = "800px")),
                              tabPanel("For Reference: Daily Cases",
                                       plotlyOutput("plot_cases", height = "800px")))),
           column(4, 
                  offset = 0,
                  style = 'padding: 20px; background-color: aliceblue',
                  htmlOutput("name_field"),
                  
                  br(),
                  fluidRow(column(12, h3("Forecasts"))),
                  

                  fluidRow(column(10,
                                  fluidRow(column(4, numericInput(inputId = "median_forecast_1", 
                                                                  value = 0,
                                                                  label = "Median 1")), 
                                           column(4, numericInput(inputId = "lower_90_forecast_1", 
                                                                  value = 0,
                                                                  label = HTML("<small>Lower 90%</small>"))),
                                           column(4, numericInput(inputId = "upper_90_forecast_1", 
                                                                  value = 0,
                                                                  label = HTML("<small>Upper 90%</small>"))))),
                           column(2, 
                                  fluidRow(column(12, actionButton(inputId = "propagate_2", "Propagate", 
                                                                   style = 'margin-top: 25px'))))),
                  fluidRow(column(10,
                                  fluidRow(column(4, numericInput(inputId = "median_forecast_2", 
                                                                  value = 0,
                                                                  label = "Median 2")), 
                                           column(4, numericInput(inputId = "lower_90_forecast_2", 
                                                                  value = 0,
                                                                  label = HTML("<small>Lower 90%</small>"))),
                                           column(4, numericInput(inputId = "upper_90_forecast_2", 
                                                                  value = 0,
                                                                  label = HTML("<small>Upper 90%</small>"))))),
                           column(2, 
                                  fluidRow(column(12, actionButton(inputId = "propagate_2", "Propagate", 
                                                                   style = 'margin-top: 25px'))))),
                  fluidRow(column(10,
                                  fluidRow(column(4, numericInput(inputId = "median_forecast_3", 
                                                                  value = 0,
                                                                  label = "Median 3")), 
                                           column(4, numericInput(inputId = "lower_90_forecast_3", 
                                                                  value = 0,
                                                                  label = HTML("<small>Lower 90%</small>"))),
                                           column(4, numericInput(inputId = "upper_90_forecast_3", 
                                                                  value = 0,
                                                                  label = HTML("<small>Upper 90%</small>"))))),
                           column(2, 
                                  fluidRow(column(12, actionButton(inputId = "propagate_3", "Propagate", 
                                                                   style = 'margin-top: 25px'))))),
                  fluidRow(column(10,
                                  fluidRow(column(4, numericInput(inputId = "median_forecast_4", 
                                                                  value = 0,
                                                                  label = "Median 4")), 
                                           column(4, numericInput(inputId = "lower_90_forecast_4", 
                                                                  value = 0,
                                                                  label = HTML("<small>Lower 90%</small>"))),
                                           column(4, numericInput(inputId = "upper_90_forecast_4", 
                                                                  value = 0,
                                                                  label = HTML("<small>Upper 90%</small>"))))),
                           column(2, 
                                  fluidRow(column(12, actionButton(inputId = "update_1", "Update", 
                                                                   style = 'margin-top: 25px')))))))

)


