fluidRow(column(8, 
                tabsetPanel(type = "tabs",
                            id = "plotpanel_q",
                            tabPanel("Make a Forecast", plotlyOutput("p_quant", height = "800px")),
                            tabPanel("For Reference: Daily Cases",
                                     plotlyOutput("plot_cases_q", height = "800px")))),
         column(4, 
                offset = 0,
                style = 'padding: 20px; background-color: aliceblue',
                
                fluidRow(column(8, htmlOutput("name_field_q")), 
                         column(4, HTML('To request a change of your user information, please write us an <a href= "mailto:nikos.bosse@lshtm.ac.uk">email</a>'))),
                
                
                br(),
                fluidRow(column(12, h3("Forecasts"))),
                
                # actionButton("button", "press"),
                
                
                fluidRow(column(9,
                                fluidRow(column(4, numericInput("median_forecast_1_q", 
                                                                value = 0,
                                                                label = "Median 1")), 
                                         column(4, numericInput(inputId = "lower_90_forecast_1_q", 
                                                                value = 0,
                                                                label = HTML("<small>Lower 90%</small>"))),
                                         column(4, numericInput(inputId = "upper_90_forecast_1_q", 
                                                                value = 0,
                                                                label = HTML("<small>Upper 90%</small>"))))),
                         column(3, 
                                fluidRow(column(12, actionButton(inputId = "propagate_1_q", "Propagate", 
                                                                 style = 'margin-top: 25px'))))),
                fluidRow(column(9,
                                fluidRow(column(4, numericInput(inputId = "median_forecast_2_q", 
                                                                value = 0,
                                                                label = "Median 2")), 
                                         column(4, numericInput(inputId = "lower_90_forecast_2_q", 
                                                                value = 0,
                                                                label = HTML("<small>Lower 90%</small>"))),
                                         column(4, numericInput(inputId = "upper_90_forecast_2_q", 
                                                                value = 0,
                                                                label = HTML("<small>Upper 90%</small>"))))),
                         column(3, 
                                fluidRow(column(12, actionButton(inputId = "propagate_2_q", "Propagate", 
                                                                 style = 'margin-top: 25px'))))),
                fluidRow(column(9,
                                fluidRow(column(4, numericInput(inputId = "median_forecast_3_q", 
                                                                value = 0,
                                                                label = "Median 3")), 
                                         column(4, numericInput(inputId = "lower_90_forecast_3_q", 
                                                                value = 0,
                                                                label = HTML("<small>Lower 90%</small>"))),
                                         column(4, numericInput(inputId = "upper_90_forecast_3_q", 
                                                                value = 0,
                                                                label = HTML("<small>Upper 90%</small>"))))),
                         column(3, 
                                fluidRow(column(12, actionButton(inputId = "propagate_3_q", "Propagate", 
                                                                 style = 'margin-top: 25px'))))),
                fluidRow(column(9,
                                fluidRow(column(4, numericInput("median_forecast_4_q", 
                                                                value = 0,
                                                                label = "Median 4")), 
                                         column(4, numericInput("lower_90_forecast_4_q", 
                                                                value = 0,
                                                                label = HTML("<small>Lower 90%</small>"))),
                                         column(4, numericInput("upper_90_forecast_4_q", 
                                                                value = 0,
                                                                label = HTML("<small>Upper 90%</small>"))))),
                         column(3, 
                                fluidRow(column(12, actionButton("update_q", HTML('<b>Update</b>'), 
                                                                 style = 'margin-top: 25px'))))), 
                br(),
                fluidRow(column(3, actionButton("submit_q", label = HTML('<b>Submit</b>'))), 
                         column(12, "(Please click 'update' before submitting)")), 
                br(), 
                br(), 
                br(), 
                fluidRow(column(12, textInput(inputId = "comments_q", 
                                              label = "Do you have any additional comments, suggestions, feedback?"))), 
                fluidRow(column(12, HTML('Preferably, you can submit an issue on <a href="https://github.com/epiforecasts/covid-german-forecasts">github</a>'))))
)









